server:
  port: 8084

spring:
   servlet:
      multipart:
         enabled: true
         file-size-threshold: 2KB
         max-file-size: 200MB
         max-request-size: 215MB

file:
   upload-dir: ./files

database:
   datasource:
      url: jdbc:mysql://localhost:3306/quanly_nguyenlieu?useUnicode=yes&characterEncoding=UTF-8
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: buithevuong
   jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true

